### ISSUE TITLE
Gateway?

### ISSUE THREAD

**Issue by Freakshows** [SpectroCoin/OpenCart-Bitcoin-Payment-Gateway-Extension#2]
Hi
Are customers redirected to a payment gateway using this extension?
Reason for asking is that when installing this on my test shop, and doing a test order, i see the option to pay with bitcoin, but no instruction, just checkout and order placed?

**Comment by devops-primary** [comment]
Hello,

 

Yes, using this payment gateway your customers will be redirected to the
payment page.

 

Regards,

 

Karolis

 

|   <mailto:info@spectrocoin.com> info@spectrocoin.com  |

| www.SpectroCoin.com  |
