### ISSUE TITLE
Order created without payment

### ISSUE THREAD

**Issue by mcarcaso** [SpectroCoin/OpenCart-Bitcoin-Payment-Gateway-Extension#3]
Hi there, I was playing around with this extension and created a test order that I abandoned at the payment step and found that the order was still created and it's unclear from the opencart dashboard whether payment was made or not. Am I expected to cross-reference payments in spectrocoin's website with the orders made on opencart or should this be done automatically somehow?

**Comment by mcarcaso** [comment]
Ping?

**Comment by devops-primary** [comment]
Hello, 

Did you create a "Test" order? If yes so order should be just test it can
not be paid. If I did not understand your question correctly so please
contact me.

Best Regards,

Karolis Merchant support specialist

 <mailto:Merchant@spectrocoin.com> Merchant@spectrocoin.com 

skype: spectrocoin_merchant

 <http://spectrocoin.com/> http://spectrocoin.com

 Spectro Finance Ltd

78 York Street, London, W1H 1DP, United Kingdom

**Comment by mcarcaso** [comment]
I was doing an end-to-end test so as far as OpenCart/SpectroCoin is concerned, it was a real order.

**Comment by ktamasauskas** [comment]
Hello,
May you have an opportunity to contact us straight by skype: spectrocoin_merchant or email: merchant@spectrocoin.com.
You can finde your order in our dashboard if it was created go to:  Merchants -> get started select your project and you should be able to find your order.  If there you can not find order so the order was not created, maybe the reason for that is bad open cart plugin configuration.

**Comment by mcarcaso** [comment]
I think the root cause of my confusion were errors that were silently happening during this process. The callbacks that spectrocoin tried to send back to my opencart server were failing and I wasn't seeing any errors in OpenCart's error logs but they were being logged in apache's server logs which lead me to a fix I'm proposing here: 
https://github.com/SpectroCoin/OpenCart-Bitcoin-Payment-Gateway-Extension/pull/4
